name: rnaseq-nf
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: unsafe-tracker ci
    # This job runs on Linux
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        java_version: ['17']

    steps:
      - name: Environment
        run: env | sort

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java_version }}
          architecture: x64

      - name: Tests
        run: |
          ./gradlew check
...
