name: unsafe-tracker
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: unsafe-tracker ci
    # This job runs on Linux
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        java_version: ['17']

    steps:
      - name: Environment
        run: env | sort

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java_version }}
          architecture: x64

      - name: Tests
        run: |
          ./gradlew check

      - name: Release
        if: "contains(github.event.head_commit.message, '[release]')"
        run: |
          bash publish.sh unsafe-tracker
          bash tag-and-push.sh
        env:
          GRADLE_OPTS: '-Dorg.gradle.daemon=false'
          AWS_ACCESS_KEY_ID: ${{secrets.TOWER_CI_AWS_ACCESS}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.TOWER_CI_AWS_SECRET}}
          AWS_DEFAULT_REGION: 'eu-west-1'
          PUBLISH_REPO_URL: "s3://maven.seqera.io/releases"

      - name: Publish tests report
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports-jdk-${{ matrix.java_version }}
          path: |
            **/build/reports/tests/test
...
